/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'totalEditions' : bigint,
  'pitchCount' : bigint,
  'inProgressCount' : bigint,
  'killedCount' : bigint,
  'overdueCount' : bigint,
  'assignedCount' : bigint,
  'publishedCount' : bigint,
  'reviewCount' : bigint,
  'totalReporters' : bigint,
  'totalStories' : bigint,
}
export interface Edition {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'date' : string,
  'createdAt' : bigint,
  'notes' : string,
  'storyIds' : Array<bigint>,
}
export interface Reporter {
  'id' : bigint,
  'active' : boolean,
  'beat' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
}
export interface ScheduleEntry {
  'id' : bigint,
  'date' : string,
  'storyId' : [] | [bigint],
  'createdAt' : bigint,
  'notes' : string,
  'timeSlot' : string,
  'entryTitle' : string,
}
export interface Story {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'section' : string,
  'deadline' : [] | [bigint],
  'updatedAt' : bigint,
  'notes' : string,
  'priority' : string,
  'reporter' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEdition' : ActorMethod<
    [string, string, string, Array<bigint>, string],
    bigint
  >,
  'createReporter' : ActorMethod<[string, string, string, boolean], bigint>,
  'createScheduleEntry' : ActorMethod<
    [string, [] | [bigint], string, string, string],
    bigint
  >,
  'createStory' : ActorMethod<
    [string, string, string, string, string, [] | [bigint], string],
    bigint
  >,
  'deleteEdition' : ActorMethod<[bigint], boolean>,
  'deleteReporter' : ActorMethod<[bigint], boolean>,
  'deleteScheduleEntry' : ActorMethod<[bigint], boolean>,
  'deleteStory' : ActorMethod<[bigint], boolean>,
  'getActiveReporters' : ActorMethod<[], Array<Reporter>>,
  'getAllEditions' : ActorMethod<[], Array<Edition>>,
  'getAllReporters' : ActorMethod<[], Array<Reporter>>,
  'getAllStories' : ActorMethod<[], Array<Story>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getEdition' : ActorMethod<[bigint], [] | [Edition]>,
  'getRecentStories' : ActorMethod<[bigint], Array<Story>>,
  'getReporter' : ActorMethod<[bigint], [] | [Reporter]>,
  'getScheduleEntriesByDate' : ActorMethod<[string], Array<ScheduleEntry>>,
  'getStoriesByReporter' : ActorMethod<[string], Array<Story>>,
  'getStoriesByStatus' : ActorMethod<[string], Array<Story>>,
  'getStory' : ActorMethod<[bigint], [] | [Story]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEdition' : ActorMethod<
    [bigint, string, string, string, Array<bigint>, string],
    boolean
  >,
  'updateReporter' : ActorMethod<
    [bigint, string, string, string, boolean],
    boolean
  >,
  'updateScheduleEntry' : ActorMethod<
    [bigint, string, [] | [bigint], string, string, string],
    boolean
  >,
  'updateStory' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [bigint], string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];