/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Reporter = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'beat' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const Edition = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'storyIds' : IDL.Vec(IDL.Nat),
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'section' : IDL.Text,
  'deadline' : IDL.Opt(IDL.Int),
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'priority' : IDL.Text,
  'reporter' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardSummary = IDL.Record({
  'totalEditions' : IDL.Nat,
  'pitchCount' : IDL.Nat,
  'inProgressCount' : IDL.Nat,
  'killedCount' : IDL.Nat,
  'overdueCount' : IDL.Nat,
  'assignedCount' : IDL.Nat,
  'publishedCount' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'totalReporters' : IDL.Nat,
  'totalStories' : IDL.Nat,
});
export const ScheduleEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'storyId' : IDL.Opt(IDL.Nat),
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'timeSlot' : IDL.Text,
  'entryTitle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEdition' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createReporter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createScheduleEntry' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createStory' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteEdition' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteReporter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteScheduleEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActiveReporters' : IDL.Func([], [IDL.Vec(Reporter)], ['query']),
  'getAllEditions' : IDL.Func([], [IDL.Vec(Edition)], ['query']),
  'getAllReporters' : IDL.Func([], [IDL.Vec(Reporter)], ['query']),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getEdition' : IDL.Func([IDL.Nat], [IDL.Opt(Edition)], ['query']),
  'getRecentStories' : IDL.Func([IDL.Nat], [IDL.Vec(Story)], ['query']),
  'getReporter' : IDL.Func([IDL.Nat], [IDL.Opt(Reporter)], ['query']),
  'getScheduleEntriesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScheduleEntry)],
      ['query'],
    ),
  'getStoriesByReporter' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
  'getStoriesByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
  'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEdition' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateReporter' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateScheduleEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateStory' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Reporter = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'beat' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const Edition = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'storyIds' : IDL.Vec(IDL.Nat),
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'section' : IDL.Text,
    'deadline' : IDL.Opt(IDL.Int),
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'priority' : IDL.Text,
    'reporter' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardSummary = IDL.Record({
    'totalEditions' : IDL.Nat,
    'pitchCount' : IDL.Nat,
    'inProgressCount' : IDL.Nat,
    'killedCount' : IDL.Nat,
    'overdueCount' : IDL.Nat,
    'assignedCount' : IDL.Nat,
    'publishedCount' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'totalReporters' : IDL.Nat,
    'totalStories' : IDL.Nat,
  });
  const ScheduleEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'storyId' : IDL.Opt(IDL.Nat),
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'timeSlot' : IDL.Text,
    'entryTitle' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEdition' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createReporter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createScheduleEntry' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createStory' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteEdition' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteReporter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteScheduleEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActiveReporters' : IDL.Func([], [IDL.Vec(Reporter)], ['query']),
    'getAllEditions' : IDL.Func([], [IDL.Vec(Edition)], ['query']),
    'getAllReporters' : IDL.Func([], [IDL.Vec(Reporter)], ['query']),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getEdition' : IDL.Func([IDL.Nat], [IDL.Opt(Edition)], ['query']),
    'getRecentStories' : IDL.Func([IDL.Nat], [IDL.Vec(Story)], ['query']),
    'getReporter' : IDL.Func([IDL.Nat], [IDL.Opt(Reporter)], ['query']),
    'getScheduleEntriesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScheduleEntry)],
        ['query'],
      ),
    'getStoriesByReporter' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
    'getStoriesByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
    'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEdition' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateReporter' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateScheduleEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateStory' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };