/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'pitchCount' : bigint,
  'inProgressCount' : bigint,
  'killedCount' : bigint,
  'overdueCount' : bigint,
  'assignedCount' : bigint,
  'publishedCount' : bigint,
  'reviewCount' : bigint,
  'totalStories' : bigint,
}
export interface ScheduleEntry {
  'id' : bigint,
  'date' : string,
  'storyId' : [] | [bigint],
  'createdAt' : bigint,
  'notes' : string,
  'timeSlot' : string,
  'entryTitle' : string,
}
export interface Story {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'section' : string,
  'deadline' : [] | [bigint],
  'updatedAt' : bigint,
  'notes' : string,
  'priority' : string,
  'reporter' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createScheduleEntry' : ActorMethod<
    [string, [] | [bigint], string, string, string],
    bigint
  >,
  'createStory' : ActorMethod<
    [string, string, string, string, string, [] | [bigint], string],
    bigint
  >,
  'deleteScheduleEntry' : ActorMethod<[bigint], boolean>,
  'deleteStory' : ActorMethod<[bigint], boolean>,
  'getAllStories' : ActorMethod<[], Array<Story>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getScheduleEntriesByDate' : ActorMethod<[string], Array<ScheduleEntry>>,
  'getStoriesByStatus' : ActorMethod<[string], Array<Story>>,
  'getStory' : ActorMethod<[bigint], [] | [Story]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateScheduleEntry' : ActorMethod<
    [bigint, string, [] | [bigint], string, string, string],
    boolean
  >,
  'updateStory' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [bigint], string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];